
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - GEMINI_API_KEY=${API_KEY}
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge