services:
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile 
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      - PORT=3001
      - GEMINI_API_KEY=${API_KEY}
      
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile 
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
